### ISSUE TITLE
'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by AF-lmf** [EugeneLiu/xiaomi_airconditioningcompanionMCN02#11]
Logger: homeassistant
Source: custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py:247
First occurred: 上午10:19:21 (2 occurrences)
Last logged: 上午10:19:28

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 266, in _async_sensor_changed
    await self._async_update_temp(new_state)
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 247, in _async_update_temp
    self._current_temperature = self.hass.config.units.temperature(
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by cls1997** [comment]
Same.
 core-homeassistant 2021.7.3
