### ISSUE TITLE
Device Support - lumi.acpartner.mcn04 / KTB04LM

### ISSUE THREAD

**Issue by johnjoemorgan** [EugeneLiu/xiaomi_airconditioningcompanionMCN02#27]
Would it be possible to expand support to the lumi.acpartner.mcn04 / KTB04LM and show current(W)?

Thanks

**Comment by johnjoemorgan** [comment]
For reference when trying to add with current component the error given is:

xiaomi_miio_airconditioningcompanionmcn02: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 323, in async_update
    if state.target_temperature <= self.max_temp else None,
  File "/usr/local/lib/python3.9/site-packages/miio/airconditioningcompanionMCN.py", line 79, in target_temperature
    return self.data[2]
IndexError: list index out of range
