### ISSUE TITLE
docker下的hass安装python-miio失败，是否只能等待新miio合并到hass里

### ISSUE THREAD

**Issue by hp6120c** [EugeneLiu/xiaomi_airconditioningcompanionMCN02#4]
你好，首先很感谢你开发了这个插件。看了上一个issue已经明白了问题，但是我pip安装python-miio失败，报的错网上也找不到原因，想问下是等hass更新依赖，还是能有别的解决办法呢，另外我是docker里的hass，但我是在系统里安装miio，我理解docker是可以和系统公用资源的，这样操作有没有问题呢

**Comment by EugeneLiu** [comment]
hass 不支持通过 pip+git 安装包，只能等待 python-miio 发布新版本，现在代码已经合并了，如发布新版本就可以使用了。目前你可以通过手动修改 site-package 中的相关源代码来实现。

**Comment by zz1123720** [comment]
新版固件报错
Logger: homeassistant.components.climate
Source: custom_components/xiaomi_miio_airconditioningcompanion/miio/airconditioningcompanionMCN.py:54
Integration: 空调 (documentation, issues)
First occurred: 下午11:40:52 (1 occurrences)
Last logged: 下午11:40:52

xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 319, in async_update
    ATTR_LOAD_POWER: state.load_power,
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/miio/airconditioningcompanionMCN.py", line 54, in load_power
    return int(self.data[-1])
IndexError: list index out of range
