### ISSUE TITLE
新版固件报错

### ISSUE THREAD

**Issue by zz1123720** [EugeneLiu/xiaomi_airconditioningcompanionMCN02#5]
Logger: homeassistant.components.climate
Source: custom_components/xiaomi_miio_airconditioningcompanion/miio/airconditioningcompanionMCN.py:54
Integration: 空调 (documentation, issues)
First occurred: 下午11:40:52 (1 occurrences)
Last logged: 下午11:40:52

xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 319, in async_update
    ATTR_LOAD_POWER: state.load_power,
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miio_airconditioningcompanion/miio/airconditioningcompanionMCN.py", line 54, in load_power
    return int(self.data[-1])
IndexError: list index out of range

**Comment by EugeneLiu** [comment]
I use 2.1.8_0003 version,no problem.
